"use client";
import { useEffect, useRef, useState } from "react";
import { Heart, Music, Volume2, VolumeX, X, Star, Sparkles, Wifi, Camera, Zap, Gamepad2, Upload, Play, Pause, SkipForward, Trash2, CalendarDays, Image as ImageIcon, Video, Disc3, ChevronLeft } from "lucide-react";

type P={id:number;name:string;apiName:string;type:string;color:string;hp:number;power:number;skill:string;sprite:string;artwork:string;cry?:string};
const base=[
[700,"Sylveon","sylveon","Hada","#f8a4d1",112,19,"Voz cautivadora"],[25,"Pikachu","pikachu","Eléctrico","#ffd84b",90,22,"Impactrueno"],[133,"Eevee","eevee","Normal","#c89a67",98,18,"Ataque rápido"],[39,"Jigglypuff","jigglypuff","Hada","#f4a9cf",115,16,"Canto"],[35,"Clefairy","clefairy","Hada","#f7b7d8",105,17,"Brillo mágico"],[37,"Vulpix","vulpix","Fuego","#e98f64",94,21,"Ascuas"],[906,"Sprigatito","sprigatito","Planta","#87d99b",97,20,"Hoja mágica"],[393,"Piplup","piplup","Agua","#79b9ef",102,18,"Pistola agua"]] as const;
const art=(id:number)=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;
const spr=(id:number)=>`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
const initial:P[]=base.map(x=>({id:x[0],name:x[1],apiName:x[2],type:x[3],color:x[4],hp:x[5],power:x[6],skill:x[7],sprite:spr(x[0]),artwork:art(x[0])}));
type Screen="title"|"map"|"battle"|"album"|"team"|"music"|"games";
type Memory={id:string,url:string,type:"image"|"video",title:string,date:string,note:string,favorite?:boolean};
type Track={id:string,url:string,name:string};
const defaults:Memory[]=[1,2,3,4].map((n,i)=>({id:`default${n}`,url:`/memories/nicole-${n}.jpeg`,type:"image",title:["Un comienzo bonito","Día especial","Corazones y aventuras","Compañía perfecta"][i],date:`2026-0${i+1}-14`,note:"Un recuerdo para guardar siempre 💗",favorite:i===0}));
const customCries:Record<number,string>={25:"/audio/pikachu.mp3",39:"/audio/jigglypuff.mp3",37:"/audio/vulpix.mp3"};
const DB_NAME="nicolle-pocket-media",STORE="memories";
function idbOpen(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveMemoryBlob(rec:{id:string;blob:Blob;type:"image"|"video";title:string;date:string;note:string;favorite?:boolean}){const db=await idbOpen();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(rec);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
async function loadMemoryBlobs(){const db=await idbOpen();const rows=await new Promise<any[]>((resolve,reject)=>{const r=db.transaction(STORE,"readonly").objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)});db.close();return rows}
async function deleteMemoryBlob(id:string){const db=await idbOpen();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
async function updateMemoryMeta(id:string,patch:Partial<Memory>){if(!id.startsWith("up"))return;const db=await idbOpen();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite"),st=tx.objectStore(STORE),r=st.get(id);r.onsuccess=()=>{if(r.result)st.put({...r.result,...patch,url:undefined})};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}

export default function Home(){
 const [dex,setDex]=useState(initial),[api,setApi]=useState(false),[screen,setScreen]=useState<Screen>("title"),[starter,setStarter]=useState(0),[enemyI,setEnemyI]=useState(2),[ph,setPh]=useState(112),[eh,setEh]=useState(98),[msg,setMsg]=useState("¡Un Eevee salvaje apareció!"),[level,setLevel]=useState(1),[xp,setXp]=useState(20),[stars,setStars]=useState(120),[caught,setCaught]=useState<number[]>([0]),[sound,setSound]=useState(true),[speaking,setSpeaking]=useState<string|null>(null),[throwing,setThrowing]=useState(false),[captured,setCaptured]=useState(false),[memories,setMemories]=useState<Memory[]>(defaults),[tracks,setTracks]=useState<Track[]>([]),[track,setTrack]=useState(0),[playing,setPlaying]=useState(false),[toast,setToast]=useState(""),[pos,setPos]=useState({x:52,y:67}),[facing,setFacing]=useState<"up"|"down"|"left"|"right">("down"),[walking,setWalking]=useState(false);
 const player=useRef<HTMLAudioElement>(null),cry=useRef<HTMLAudioElement|null>(null); const hero=dex[starter],enemy=dex[enemyI];
 useEffect(()=>{Promise.all(base.map(async x=>{try{const r=await fetch(`https://pokeapi.co/api/v2/pokemon/${x[2]}`),d=await r.json();return {...initial.find(p=>p.id===x[0])!,sprite:d.sprites.front_default||spr(x[0]),artwork:d.sprites.other?.["official-artwork"]?.front_default||art(x[0]),cry:d.cries?.latest||d.cries?.legacy}}catch{return initial.find(p=>p.id===x[0])!}})).then(d=>{setDex(d);setApi(d.some(p=>p.cry))})},[]);
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem("nicolle-pocket-v3")||"{}");if(p.level){setLevel(p.level);setXp(p.xp);setStars(p.stars);setCaught(p.caught);setStarter(p.starter)}}catch{}},[]);
 useEffect(()=>localStorage.setItem("nicolle-pocket-v3",JSON.stringify({level,xp,stars,caught,starter})),[level,xp,stars,caught,starter]);
 useEffect(()=>{loadMemoryBlobs().then(rows=>{if(rows.length){const restored:Memory[]=rows.map(r=>({id:r.id,url:URL.createObjectURL(r.blob),type:r.type,title:r.title,date:r.date,note:r.note,favorite:r.favorite}));setMemories(m=>[...restored,...m.filter(x=>!x.id.startsWith("up"))])}}).catch(()=>{})},[]);
 useEffect(()=>()=>{[...memories.filter(m=>m.id.startsWith("up")),...tracks].forEach(x=>URL.revokeObjectURL(x.url))},[]);
 const say=(t:string)=>{setToast(t);setTimeout(()=>setToast(""),1800)};
 const playCry=(p:P)=>{if(!sound)return;cry.current?.pause();setSpeaking(p.name);const src=customCries[p.id]||p.cry||`https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/${p.id}.ogg`;const a=new Audio(src);cry.current=a;a.volume=customCries[p.id]?.startsWith("/audio/") ? .72 : .34;a.playbackRate=1;a.play().catch(()=>{});a.onended=()=>setSpeaking(null);setTimeout(()=>setSpeaking(null),2200)};
 const encounter=()=>{const opts=dex.map((_,i)=>i).filter(i=>i!==starter),i=opts[Math.floor(Math.random()*opts.length)];setEnemyI(i);setEh(dex[i].hp);setPh(hero.hp);setCaptured(false);setThrowing(false);setMsg(`¡Un ${dex[i].name} salvaje apareció!`);setScreen("battle");setTimeout(()=>playCry(dex[i]),300)};
 const attack=(special=false)=>{if(eh<=0||ph<=0||captured)return;const hit=hero.power+Math.floor(Math.random()*9)+(special?8:0),n=Math.max(0,eh-hit);setEh(n);setMsg(`${hero.name} usó ${special?hero.skill:"Ataque rápido"}. ¡${hit} de daño!`);if(!n){setStars(s=>s+25);setXp(v=>{const z=v+35;if(z>=100){setLevel(l=>l+1);return z-100}return z});return}setTimeout(()=>{const h=Math.max(5,enemy.power-7+Math.floor(Math.random()*8));setPh(v=>Math.max(0,v-h));setMsg(`${enemy.name} contraataca. ¡Tú puedes, ${hero.name}!`)},650)};
 const capture=()=>{if(eh>enemy.hp*.42)return setMsg("Debilítalo hasta dejar su barra amarilla o roja 💗");if(stars<20)return setMsg("Necesitas 20 estrellas para una Poké Ball.");setStars(s=>s-20);setThrowing(true);setMsg("¡Poké Ball lanzada!");setTimeout(()=>{const ok=Math.random()>.18;setThrowing(false);if(ok){setCaptured(true);setCaught(c=>[...new Set([...c,enemyI])]);setMsg(`¡Perfecto! ${enemy.name} fue capturado ✨`)}else setMsg(`${enemy.name} salió de la Poké Ball. ¡Otra vez!`)},2100)};
 const uploadMemory=async(files:FileList|null)=>{if(!files)return;const valid=[...files].filter(f=>f.type.startsWith("image/")||f.type.startsWith("video/"));const add:Memory[]=[];for(const f of valid){const id="up"+crypto.randomUUID(),type=(f.type.startsWith("video/")?"video":"image") as "video"|"image",title=f.name.replace(/\.[^.]+$/,""),date=new Date().toISOString().slice(0,10),note="Nuevo recuerdo de Nicolle ✨";await saveMemoryBlob({id,blob:f,type,title,date,note,favorite:false});add.push({id,url:URL.createObjectURL(f),type,title,date,note,favorite:false})}setMemories(m=>[...add,...m]);say(`${add.length} recuerdo(s) guardado(s) en este dispositivo`) };
 const uploadMusic=(files:FileList|null)=>{if(!files)return;const add=[...files].filter(f=>f.type.startsWith("audio/")).map(f=>({id:crypto.randomUUID(),url:URL.createObjectURL(f),name:f.name.replace(/\.[^.]+$/,"")}));setTracks(t=>[...t,...add]);say(`${add.length} canción(es) agregada(s)`) };
 const playTrack=(i=track)=>{if(!tracks.length)return say("Primero agrega una canción");setTrack(i);setTimeout(()=>{player.current?.play();setPlaying(true)},30)};

 const move=(dir:"up"|"down"|"left"|"right")=>{if(screen!=="map")return;setFacing(dir);setWalking(true);setTimeout(()=>setWalking(false),180);setPos(v=>{const step=5;return {x:Math.max(8,Math.min(92,v.x+(dir==="left"?-step:dir==="right"?step:0))),y:Math.max(20,Math.min(84,v.y+(dir==="up"?-step:dir==="down"?step:0)))}})};
 const interact=()=>{if(screen!=="map"){if(screen!=="title")setScreen("map");return}const spots=[{x:23,y:34,fn:encounter,label:"Zona Pokémon"},{x:78,y:54,fn:()=>setScreen("games"),label:"Villa de Juegos"},{x:22,y:76,fn:()=>setScreen("album"),label:"Casa de Recuerdos"},{x:76,y:76,fn:()=>setScreen("music"),label:"Rincón Musical"}];const near=spots.map(z=>({...z,d:Math.hypot(pos.x-z.x,pos.y-z.y)})).sort((a,b)=>a.d-b.d)[0];if(near&&near.d<22){say(`Entrando a ${near.label} ✨`);near.fn()}else{playCry(hero);say(`${hero.name} está listo para explorar 💗`)}};
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(screen!=="map")return;const k=e.key.toLowerCase();if(["arrowup","w"].includes(k)){e.preventDefault();move("up")}else if(["arrowdown","s"].includes(k)){e.preventDefault();move("down")}else if(["arrowleft","a"].includes(k)){e.preventDefault();move("left")}else if(["arrowright","d"].includes(k)){e.preventDefault();move("right")}else if(["enter"," "].includes(k)){e.preventDefault();interact()}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[screen,pos,hero]);
 const nav=(s:Screen)=>setScreen(s);
 return <main className="page"><audio ref={player} src={tracks[track]?.url} onEnded={()=>tracks.length&&playTrack((track+1)%tracks.length)}/><PokemonRing dex={dex} speaking={speaking} play={playCry}/><section className="console"><header className="top"><span><Heart size={13} fill="currentColor"/> NICOLLE POCKET</span><div className={`apiStatus ${api?"online":""}`}><Wifi size={11}/>{api?"POKÉDEX ONLINE":"CARGANDO"}</div><b>•••••</b></header><div className="frame"><div className="screen">
 {screen==="title"&&<Title dex={dex} go={()=>nav("map")} choose={i=>{setStarter(i);setCaught([i]);setPh(dex[i].hp);nav("map");playCry(dex[i])}} play={playCry}/>} 
 {screen==="map"&&<Map hero={hero} level={level} xp={xp} stars={stars} battle={encounter} nav={nav} play={playCry} pos={pos} facing={facing} walking={walking}/>} 
 {screen==="battle"&&<Battle hero={hero} enemy={enemy} ph={ph} eh={eh} msg={msg} attack={attack} capture={capture} leave={()=>nav("map")} again={encounter} play={playCry} throwing={throwing} captured={captured}/>} 
 {screen==="album"&&<Album memories={memories} back={()=>nav("map")} upload={uploadMemory} setMemories={setMemories}/>} 
 {screen==="team"&&<Team dex={dex} caught={caught} back={()=>nav("map")} select={i=>{setStarter(i);setPh(dex[i].hp);nav("map")}} play={playCry}/>} 
 {screen==="music"&&<MusicRoom tracks={tracks} track={track} playing={playing} back={()=>nav("map")} upload={uploadMusic} play={playTrack} toggle={()=>{if(playing)player.current?.pause();else player.current?.play();setPlaying(!playing)}} next={()=>playTrack((track+1)%tracks.length)} remove={i=>{setTracks(t=>t.filter((_,j)=>j!==i));if(i===track){player.current?.pause();setPlaying(false);setTrack(0)}}}/>} 
 {screen==="games"&&<MiniGames back={()=>nav("map")} reward={n=>{setStars(s=>s+n);say(`+${n} estrellas ✨`)}}/>}
 </div></div><div className="controls"><div className="dpad"><button onClick={()=>move("up")}>▲</button><button onClick={()=>move("left")}>◀</button><button className="dcenter" onClick={interact}>◆</button><button onClick={()=>move("right")}>▶</button><button onClick={()=>move("down")}>▼</button></div><div className="sys"><button onClick={()=>nav("music")}><Music/></button><button onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}</button><small>SELECT　START</small></div><div className="ab"><button onClick={()=>nav("map")}>B</button><button onClick={interact}>A</button></div></div><footer>✦ FOR NICOLLE, WITH MAGIC ✦</footer></section>{toast&&<div className="voiceToast">{toast}</div>}{speaking&&<div className="voiceToast"><Volume2 size={14}/> {speaking}</div>}<p className="hint">Explora el mapa · escucha Pokémon · guarda recuerdos · reproduce tu música · juega minijuegos</p></main>
}
function PokemonRing({dex,speaking,play}:{dex:P[];speaking:string|null;play:(p:P)=>void}){return <div className="pokemonRing">{dex.map((p,i)=><button key={p.id} className={`orbitPokemon p${i} ${speaking===p.name?"speaking":""}`} onClick={()=>play(p)}><img src={p.artwork}/><span><Volume2 size={11}/>{p.name}</span></button>)}</div>}
function Title({dex,go,choose,play}:{dex:P[];go:()=>void;choose:(i:number)=>void;play:(p:P)=>void}){const[pick,setPick]=useState(false);return <div className="title interactiveTitle"><div className="titleSky"><span>✦</span><span>♡</span><span>✦</span></div><button className="heroPokemon" onClick={()=>play(dex[0])}><div className="halo"/><img src={dex[0].artwork}/></button><small>UNA AVENTURA POKÉMON ESPECIAL</small><h1>El mundo mágico<br/><b>de Nicolle</b></h1><p>Recuerdos, música, combates y minijuegos en un solo mundo.</p>{!pick?<div className="titlebuttons"><button onClick={()=>setPick(true)}>NUEVA AVENTURA <Sparkles/></button><button onClick={go}>CONTINUAR</button></div>:<div className="starters"><b>Elige tu compañero</b><div>{dex.slice(0,3).map((p,i)=><button key={p.id} onClick={()=>choose(i)}><img src={p.sprite}/><strong>{p.name}</strong><small>{p.type}</small></button>)}</div></div>}<label>TOCA A SYLVEON · LOS ELEMENTOS ESTÁN VIVOS</label></div>}
function Map({hero,level,xp,stars,battle,nav,play,pos,facing,walking}:{hero:P;level:number;xp:number;stars:number;battle:()=>void;nav:(s:Screen)=>void;play:(p:P)=>void;pos:{x:number;y:number};facing:"up"|"down"|"left"|"right";walking:boolean}){return <div className="map"><header><div className="avatarN">N</div><div><b>Nicolle</b><small>Nivel {level} · Entrenadora rosa</small></div><span><Star fill="currentColor"/>{stars}</span></header><div className="xp"><i style={{width:xp+"%"}}/><small>{xp}/100 EXP</small></div><section className="world"><div className="cloud c1"/><div className="cloud c2"/><div className="mountain m1"/><div className="mountain m2"/><div className="lakeShape"/><div className="path"/><div className="flowers f1">✿ ✿ ✿</div><div className="flowers f2">✿ ✿</div><button className="place garden" onClick={battle}><span className="placeIcon">🌸</span><b>Zona Pokémon</b><small>¡Explorar!</small></button><button className="place lake" onClick={()=>nav("games")}><span className="placeIcon">🎡</span><b>Villa de Juegos</b><small>5 minijuegos</small></button><button className="place house" onClick={()=>nav("album")}><span className="placeIcon">🏡</span><b>Casa de Recuerdos</b></button><button className="place musicSpot" onClick={()=>nav("music")}><span className="placeIcon">🎵</span><b>Rincón Musical</b></button><div className={`player mapHero face-${facing} ${walking?"walking":""}`} style={{left:`${pos.x}%`,top:`${pos.y}%`}}><span className="shadowP"/><button onClick={()=>play(hero)}><img src={hero.artwork}/></button><small>{hero.name}</small><div className="stepSpark">✦</div></div><div className="mapTip">Flechas: caminar · A: interactuar</div></section><nav><button onClick={battle}>⚔️<small>Combate</small></button><button onClick={()=>nav("team")}>💗<small>Equipo</small></button><button onClick={()=>nav("album")}><Camera/><small>Álbum</small></button><button onClick={()=>nav("music")}><Music/><small>Música</small></button><button onClick={()=>nav("games")}><Gamepad2/><small>Juegos</small></button></nav></div>}
function Hp({v,m}:{v:number;m:number}){return <div className="hp"><i style={{width:Math.max(0,v/m*100)+"%",background:v/m<.3?"#ff4d68":v/m<.55?"#ffbd3e":"#55d68b"}}/></div>}
function Battle({hero,enemy,ph,eh,msg,attack,capture,leave,again,play,throwing,captured}:{hero:P;enemy:P;ph:number;eh:number;msg:string;attack:(s?:boolean)=>void;capture:()=>void;leave:()=>void;again:()=>void;play:(p:P)=>void;throwing:boolean;captured:boolean}){const end=eh<=0||ph<=0||captured;return <div className="battle goBattle"><header><button onClick={leave}>‹ MAPA</button><b>ENCUENTRO AR</b><span>● REC</span></header><section className="arena goArena"><div className="battleRings"/><div className="ecard"><b>{enemy.name}</b><small>NV. 3 · {enemy.type}</small><Hp v={eh} m={enemy.hp}/></div><button className={`wild ${captured?"caughtAnim":""}`} onClick={()=>play(enemy)}><img src={enemy.artwork}/></button><button className="fighter" onClick={()=>play(hero)}><img src={hero.artwork}/></button><div className="hcard"><b>{hero.name}</b><small>NV. 5 · {hero.type}</small><Hp v={ph} m={hero.hp}/><label>{ph}/{hero.hp} HP</label></div>{throwing&&<div className="pokeballThrow">◓</div>}{captured&&<div className="captureBurst">✦ CAPTURADO ✦</div>}</section><p className="message">{msg}</p><div className="moves">{!end?<><button onClick={()=>attack()}><Zap/> ATAQUE</button><button onClick={()=>attack(true)}><Sparkles/> ESPECIAL</button><button className="captureBtn" onClick={capture}>◓ LANZAR BALL</button><button onClick={leave}>HUIR</button></>:<><button onClick={again}>OTRO ENCUENTRO</button><button onClick={leave}>VOLVER AL MAPA</button></>}</div></div>}
function Head({back,title,sub}:{back:()=>void;title:string;sub:string}){return <header><button onClick={back}><ChevronLeft/></button><div><b>{title}</b><small>{sub}</small></div><Sparkles/></header>}
function Album({memories,back,upload,setMemories}:{memories:Memory[];back:()=>void;upload:(f:FileList|null)=>void;setMemories:React.Dispatch<React.SetStateAction<Memory[]>>}){
 const [year,setYear]=useState("Todos"),[tab,setTab]=useState<"timeline"|"photos"|"videos"|"favorites">("timeline"),[open,setOpen]=useState<Memory|null>(null);
 const years=["Todos",...new Set(memories.map(m=>m.date.slice(0,4)).sort().reverse())];
 const filtered=memories.filter(m=>(year==="Todos"||m.date.startsWith(year))&&(tab==="timeline"||tab==="photos"&&m.type==="image"||tab==="videos"&&m.type==="video"||tab==="favorites"&&m.favorite)).sort((a,b)=>b.date.localeCompare(a.date));
 const groups=Object.entries(filtered.reduce((a,m)=>{const k=m.date.slice(0,7);(a[k]??=[]).push(m);return a},{} as Record<string,Memory[]>));
 const edit=(patch:Partial<Memory>)=>{if(!open)return;const next={...open,...patch};setOpen(next);setMemories(ms=>ms.map(m=>m.id===open.id?next:m));updateMemoryMeta(open.id,patch).catch(()=>{})};
 const remove=async(m:Memory)=>{if(m.id.startsWith("up"))await deleteMemoryBlob(m.id).catch(()=>{});if(m.id.startsWith("up"))URL.revokeObjectURL(m.url);setMemories(ms=>ms.filter(x=>x.id!==m.id));setOpen(null)};
 return <div className="collection albumPro"><Head back={back} title="Álbum de Recuerdos" sub="Fotos y videos guardados por mes y año"/>
 <div className="albumStats"><span><b>{memories.length}</b><small>recuerdos</small></span><span><b>{memories.filter(m=>m.type==="image").length}</b><small>fotos</small></span><span><b>{memories.filter(m=>m.type==="video").length}</b><small>videos</small></span><span><b>✓</b><small>guardado local</small></span></div>
 <div className="albumTabs"><button className={tab==="timeline"?"active":""} onClick={()=>setTab("timeline")}>Línea de tiempo</button><button className={tab==="photos"?"active":""} onClick={()=>setTab("photos")}>Fotos</button><button className={tab==="videos"?"active":""} onClick={()=>setTab("videos")}>Videos</button><button className={tab==="favorites"?"active":""} onClick={()=>setTab("favorites")}>♡ Favoritos</button></div>
 <div className="albumTools"><label><Upload/> Nuevo recuerdo<input hidden multiple type="file" accept="image/*,video/*" onChange={e=>{upload(e.target.files);e.currentTarget.value=""}}/></label><select value={year} onChange={e=>setYear(e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></div>
 <div className="timeline">{groups.length?groups.map(([ym,items])=><section key={ym}><div className="monthTitle"><CalendarDays/><div><b>{new Date(ym+"-02T12:00").toLocaleDateString("es",{month:"long",year:"numeric"})}</b><small>{items!.length} recuerdos</small></div></div><div className="memoryGrid">{items!.map(m=><button key={m.id} className="memoryCard" onClick={()=>setOpen(m)}>{m.type==="video"?<><video src={m.url}/><Video/></>:<><img src={m.url}/><ImageIcon/></>}<i className={m.favorite?"fav on":"fav"}>♥</i><span><b>{m.title}</b><small>{new Date(m.date+"T12:00").toLocaleDateString("es",{day:"2-digit",month:"short",year:"numeric"})}</small></span></button>)}</div></section>):<div className="albumEmpty">💗<b>No hay recuerdos aquí todavía</b><small>Sube una foto o video para comenzar este capítulo.</small></div>}</div>
 {open&&<div className="memoryViewer"><div className="viewerTop"><button onClick={()=>setOpen(null)}><X/></button><button className={open.favorite?"favoriteOn":""} onClick={()=>edit({favorite:!open.favorite})}>♥</button></div>{open.type==="video"?<video src={open.url} controls autoPlay/>:<img src={open.url}/>}<label>Título<input value={open.title} onChange={e=>edit({title:e.target.value})}/></label><label>Fecha<input type="date" value={open.date} onChange={e=>edit({date:e.target.value})}/></label><label>Historia<textarea value={open.note} onChange={e=>edit({note:e.target.value})}/></label>{open.id.startsWith("up")&&<button className="deleteMemory" onClick={()=>remove(open)}><Trash2/> Eliminar recuerdo</button>}<small className="savedNote">✓ Los recuerdos subidos permanecen después de actualizar la página en este navegador.</small></div>}</div>}
function Team({dex,caught,back,select,play}:{dex:P[];caught:number[];back:()=>void;select:(i:number)=>void;play:(p:P)=>void}){return <div className="collection"><Head back={back} title="Mis Pokémon" sub={`${caught.length} compañeros capturados`}/><div className="team">{dex.map((p,i)=>{const own=caught.includes(i);return <div className={`teamCard ${own?"":"locked"}`} key={p.id}><button className="cryMini" onClick={()=>own&&play(p)}><Volume2/></button><button className="teamSelect" disabled={!own} onClick={()=>select(i)}><span style={{background:p.color+"25"}}>{own?<img src={p.artwork}/>:"?"}</span><b>{own?p.name:"Desconocido"}</b><small>{own?`${p.type} · ${p.skill}`:"Encuéntralo explorando"}</small></button></div>})}</div></div>}
function MusicRoom({tracks,track,playing,back,upload,play,toggle,next,remove}:{tracks:Track[];track:number;playing:boolean;back:()=>void;upload:(f:FileList|null)=>void;play:(i?:number)=>void;toggle:()=>void;next:()=>void;remove:(i:number)=>void}){return <div className="collection musicRoom"><Head back={back} title="Nicolle Music" sub="Tu música mientras juegas"/><div className="record"><Disc3 className={playing?"spin":""}/><small>REPRODUCIENDO</small><b>{tracks[track]?.name||"Tu playlist personal"}</b><div><button onClick={toggle}>{playing?<Pause/>:<Play/>}</button><button onClick={next}><SkipForward/></button></div></div><label className="uploadMusic"><Upload/> AGREGAR MÚSICA DESDE MI EQUIPO<input hidden multiple type="file" accept="audio/*" onChange={e=>upload(e.target.files)}/></label><div className="trackList">{tracks.length?tracks.map((t,i)=><div className={i===track?"active":""} key={t.id}><button onClick={()=>play(i)}><Music/><span><b>{t.name}</b><small>{i===track&&playing?"Sonando ahora":"Tocar canción"}</small></span></button><button onClick={()=>remove(i)}><Trash2/></button></div>):<p>Sube MP3, M4A, WAV u otro audio compatible con tu navegador. La música seguirá sonando al volver al mapa.</p>}</div></div>}
function MiniGames({back,reward}:{back:()=>void;reward:(n:number)=>void}){const [game,setGame]=useState<number|null>(null),[levels,setLevels]=useState<number[]>(()=>{try{return JSON.parse(localStorage.getItem("nicolle-minigame-levels")||"[1,1,1,1,1]")}catch{return [1,1,1,1,1]}});const games=["Atrapa Corazones","Parejas Pokémon","Jardín Mágico","Estrellas de Nicolle","Pastelería Rosa"];const complete=(i:number,n:number)=>{reward(n);setLevels(ls=>{const v=ls.map((x,j)=>j===i?Math.min(10,x+1):x);localStorage.setItem("nicolle-minigame-levels",JSON.stringify(v));return v})};return <div className="collection games"><Head back={back} title="Villa de Minijuegos" sub="5 aventuras · niveles · récords · recompensas"/>{game===null?<div className="gameMenu proGames">{games.map((g,i)=><button key={g} onClick={()=>setGame(i)}><span>{["💗","🎴","🌷","✨","🧁"][i]}</span><div><b>{g}</b><small>Nivel {levels[i]} · {['Reflejos y precisión','Memoria Pokémon','Cuida y combina','Velocidad estelar','Pedidos y decoración'][i]}</small><em>JUGAR ▶</em></div></button>)}</div>:<Game game={game} name={games[game]} level={levels[game]} close={()=>setGame(null)} complete={n=>complete(game,n)}/>}</div>}
function Game({game,name,level,close,complete}:{game:number;name:string;level:number;close:()=>void;complete:(n:number)=>void}){
 const target=Math.min(8+level*2,24),[score,setScore]=useState(0),[time,setTime]=useState(Math.max(16,28-level)),[done,setDone]=useState(false),[heartPos,setHeartPos]=useState({x:50,y:50});
 const icons=["🌸","💗","✨","🎀","🌷","⭐"],pairCount=Math.min(3+Math.ceil(level/2),6),[cards,setCards]=useState<string[]>(()=>[...icons.slice(0,pairCount),...icons.slice(0,pairCount)].sort(()=>Math.random()-.5)),[open,setOpen]=useState<number[]>([]),[matched,setMatched]=useState<number[]>([]);
 const [garden,setGarden]=useState(0),gardenGoal=Math.min(5+level,12),[starsCaught,setStarsCaught]=useState(0),[starPos,setStarPos]=useState({x:30,y:40});
 const toppings=["🍓","🍫","🍒","🌈","💖"],order=toppings[level%toppings.length],[cake,setCake]=useState<string[]>([]),cakeGoal=Math.min(4+Math.floor(level/2),8);
 useEffect(()=>{if(done||game===1||game===2||game===4)return;const t=setInterval(()=>setTime(v=>v<=1?0:v-1),1000);return()=>clearInterval(t)},[done,game]);
 useEffect(()=>{if(time===0&&!done)setDone(true)},[time,done]);
 const win=(reward=10+level*2)=>{if(done)return;setDone(true);complete(reward)};
 const hitHeart=()=>{const n=score+1;setScore(n);setHeartPos({x:10+Math.random()*80,y:16+Math.random()*68});if(n>=target)win()};
 const flip=(i:number)=>{if(open.includes(i)||matched.includes(i)||open.length>=2||done)return;const n=[...open,i];setOpen(n);if(n.length===2)setTimeout(()=>{if(cards[n[0]]===cards[n[1]]){const mm=[...matched,...n];setMatched(mm);if(mm.length===cards.length)win(14+level*2)}setOpen([])},520)};
 const catchStar=()=>{const n=starsCaught+1;setStarsCaught(n);setStarPos({x:8+Math.random()*84,y:18+Math.random()*70});if(n>=target)win()};
 const addTop=(t:string)=>{if(done)return;const n=[...cake,t];setCake(n);if(n.length>=cakeGoal){if(n.filter(x=>x===order).length>=Math.ceil(cakeGoal*.6))win(16+level*2);else{setCake([])}}};
 return <div className="gamePlay proGamePlay"><div className="gameHud"><button className="gameBack" onClick={close}>‹ VILLA</button><span>NIVEL <b>{level}</b></span>{![1,2,4].includes(game)&&<span>⏱ <b>{time}s</b></span>}<span>⭐ <b>{score||starsCaught||matched.length/2||garden||cake.length}</b></span></div><h2>{name}</h2>
 {done&&<div className="gameResult"><span>{(game===0?score>=target:game===1?matched.length===cards.length:game===2?garden>=gardenGoal:game===3?starsCaught>=target:cake.length>=cakeGoal)?"🏆":"⏰"}</span><b>{(score>=target||matched.length===cards.length||garden>=gardenGoal||starsCaught>=target||cake.length>=cakeGoal)?"¡Nivel completado!":"Fin de la ronda"}</b><small>{(score>=target||matched.length===cards.length||garden>=gardenGoal||starsCaught>=target||cake.length>=cakeGoal)?"Desbloqueaste el siguiente nivel y ganaste estrellas.":"Vuelve a intentarlo, cada ronda te hace mejor."}</small><button onClick={close}>VOLVER A LA VILLA</button></div>}
 {!done&&game===0&&<><p>Atrapa {target} corazones antes de que termine el tiempo.</p><div className="playField heartField"><button className="movingTarget" style={{left:`${heartPos.x}%`,top:`${heartPos.y}%`}} onClick={hitHeart}>💗</button><div className="fieldScore">{score}/{target}</div></div></>}
 {!done&&game===1&&<><p>Encuentra todas las parejas. Las cartas cambian en cada nivel.</p><div className="cardsGame proCards">{cards.map((c,i)=><button className={matched.includes(i)?"matched":""} key={i} onClick={()=>flip(i)}>{open.includes(i)||matched.includes(i)?c:"✦"}</button>)}</div></>}
 {!done&&game===2&&<><p>Haz crecer el jardín con agua, sol y cariño.</p><div className="gardenScene"><div className="gardenSky">☀️ ☁️</div><div className="gardenPlants">{Array.from({length:gardenGoal},(_,i)=><span key={i}>{i<garden?(i<gardenGoal-2?"🌱":"🌷"):"·"}</span>)}</div></div><div className="gardenActions"><button onClick={()=>{const n=Math.min(gardenGoal,garden+1);setGarden(n);if(n>=gardenGoal)win()}}>💧 Regar</button><button onClick={()=>{const n=Math.min(gardenGoal,garden+1);setGarden(n);if(n>=gardenGoal)win()}}>☀️ Luz</button><button onClick={()=>{const n=Math.min(gardenGoal,garden+1);setGarden(n);if(n>=gardenGoal)win()}}>💗 Cuidar</button></div></>}
 {!done&&game===3&&<><p>Recoge {target} estrellas mágicas antes de que se apague el cielo.</p><div className="playField starField"><button className="movingTarget starTarget" style={{left:`${starPos.x}%`,top:`${starPos.y}%`}} onClick={catchStar}>⭐</button><div className="fieldScore">{starsCaught}/{target}</div></div></>}
 {!done&&game===4&&<><p>Pedido: prepara un cupcake con mayoría de <b>{order}</b> · {cakeGoal} ingredientes.</p><div className="bakery"><div className="cupcakeBuild">🧁<span>{cake.join("")}</span></div><div className="toppingBar">{toppings.map(t=><button key={t} onClick={()=>addTop(t)}>{t}</button>)}</div><small>{cake.length}/{cakeGoal} ingredientes · si el pedido falla, puedes intentarlo otra vez.</small></div></>}
 </div>}

